name: dds
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - certifi=2024.8.30
  - comm=0.2.2
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20191231
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.45.3
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - matplotlib-inline=0.1.7
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.11.9
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.1.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - accelerate==0.33.0
      - aiobotocore==2.17.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - anndata==0.11.3
      - annotated-types==0.7.0
      - array-api-compat==1.10.0
      - attrs==24.3.0
      - beautifulsoup4==4.12.3
      - biopython==1.85
      - botocore==1.35.93
      - botorch==0.12.0
      - catboost==1.2.7
      - cellxgene-census==1.15.0
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - dataclasses==0.6
      - datasets==2.19.2
      - dgl==2.1.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - easydict==1.13
      - et-xmlfile==2.0.0
      - evaluate==0.4.2
      - filelock==3.13.1
      - fonttools==4.55.2
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - fuzzywuzzy==0.18.0
      - gemmi==0.7.0
      - gget==0.29.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gpytorch==1.13
      - graphviz==0.21
      - h5py==3.12.1
      - huggingface-hub==0.27.1
      - idna==3.10
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - ipywidgets==8.1.5
      - jaxtyping==0.2.19
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - legacy-api-wrap==1.4.1
      - linear-operator==0.5.3
      - llvmlite==0.43.0
      - lxml==5.3.0
      - markupsafe==2.1.5
      - matplotlib==3.9.3
      - meeko==0.6.1
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.16
      - mysql-connector-python==9.1.0
      - natsort==8.4.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==10.2.0
      - plotly==5.24.1
      - propcache==0.2.1
      - protobuf==5.29.2
      - py3dmol==2.4.2
      - pyarrow==18.1.0
      - pyarrow-hotfix==0.6
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pynndescent==0.5.13
      - pyparsing==3.2.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pystow==0.6.1
      - pytdc==1.1.5
      - pytz==2024.2
      - pyyaml==6.0.2
      - rdkit==2023.9.6
      - regex==2024.11.6
      - requests==2.32.3
      - s3fs==2024.2.0
      - safetensors==0.5.2
      - scanpy==1.10.4
      - scikit-learn==1.2.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentry-sdk==2.19.2
      - session-info==1.0.0
      - setproctitle==1.3.4
      - smmap==5.0.1
      - somacore==1.0.11
      - soupsieve==2.6
      - statsmodels==0.14.4
      - stdlib-list==0.11.0
      - sympy==1.13.1
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - tiledb==0.29.1
      - tiledbsoma==1.11.4
      - tokenizers==0.19.1
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchdata==0.9.0
      - torchvision==0.17.1
      - tqdm==4.67.1
      - transformers==4.43.4
      - triton==2.2.0
      - typeguard==4.4.1
      - tzdata==2024.2
      - umap-learn==0.5.7
      - urllib3==2.2.3
      - useful-rdkit-utils==0.74
      - wandb==0.19.1
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.18.3
